spring.application.name=myFashionTrunk
spring.datasource.name=my_fashion_trunk
spring.datasource.url=jdbc:postgresql://localhost:5432/my_fashion_trunk

spring.jpa.hibernate.ddl-auto=update
spring.cloud.gcp.vision.enabled=true